version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: always
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    networks: 
      - app-network
    ports:
    - 3306:3306
    volumes:
      - ./mariadb/mysql/initdb/:/docker-entrypoint-initdb.d
      - ./mariadb/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel

networks:
  app-network:
    driver: bridge